// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6EPJ87cERksWMTsjTGaz4_0ERcV8vLdk',
    appId: '1:152756543521:web:d2feead0356e02a2318360',
    messagingSenderId: '152756543521',
    projectId: 'ai-teacher-707a1',
    authDomain: 'ai-teacher-707a1.firebaseapp.com',
    storageBucket: 'ai-teacher-707a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbTVrSCp2KoI_4GmOfT-X-RZwyW6Dh3hE',
    appId: '1:152756543521:android:7e00692077b8316c318360',
    messagingSenderId: '152756543521',
    projectId: 'ai-teacher-707a1',
    storageBucket: 'ai-teacher-707a1.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6EPJ87cERksWMTsjTGaz4_0ERcV8vLdk',
    appId: '1:152756543521:web:06a307ba64a1dc71318360',
    messagingSenderId: '152756543521',
    projectId: 'ai-teacher-707a1',
    authDomain: 'ai-teacher-707a1.firebaseapp.com',
    storageBucket: 'ai-teacher-707a1.appspot.com',
  );

}